
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createHmac } from "node:crypto";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.38.5";

const corsHeaders = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
    // Handle CORS
    if (req.method === 'OPTIONS') {
        return new Response('ok', { headers: corsHeaders })
    }

    try {
        const { orderId, paymentId, signature } = await req.json();

        if (!orderId || !paymentId || !signature) {
            throw new Error("Missing required payment details");
        }

        const secret = Deno.env.get("RAZORPAY_KEY_SECRET") ?? "";
        if (!secret) {
            throw new Error("Server misconfiguration: Missing Razorpay secret");
        }

        // Verify signature
        // The signature is generated by hashing "order_id|payment_id" with the key_secret
        const generated_signature = createHmac("sha256", secret)
            .update(orderId + "|" + paymentId)
            .digest("hex");

        if (generated_signature !== signature) {
            console.error("Signature verification failed. Expected:", generated_signature, "Received:", signature);
            throw new Error("Invalid payment signature");
        }

        // Initialize Supabase Admin Client
        const supabase = createClient(
            Deno.env.get("SUPABASE_URL") ?? "",
            Deno.env.get("SUPABASE_SERVICE_KEY") ?? ""
        );

        console.log(`Verifying order ${orderId} as paid...`);

        // Update order status to 'paid'
        const { data, error: updateError } = await supabase
            .from("orders")
            .update({
                status: "paid",
                updated_at: new Date().toISOString()
            })
            .eq("razorpay_order_id", orderId)
            .select();

        if (updateError) {
            console.error("Database update error:", updateError);
            throw updateError;
        }

        // Also try to insert/upsert into payments table to ensure record exists
        // We don't have all webhook details here, but we have the basics
        await supabase.from("payments").upsert({
            payment_id: paymentId,
            order_id: orderId,
            amount: 0, // We might not have the amount here, but better to have the record. Webhook will update it fully.
            status: 'captured',
            created_at: new Date().toISOString()
        }, { onConflict: 'payment_id', ignoreDuplicates: true });

        return new Response(JSON.stringify({ success: true, order: data }), {
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            status: 200
        });

    } catch (error: any) {
        console.error("Verification error:", error);
        return new Response(JSON.stringify({ error: error.message }), {
            headers: { ...corsHeaders, 'Content-Type': 'application/json' },
            status: 400
        });
    }
})
